Algoritmo "Aumento Salario"

Var

salario, aumento, valor : real

Inicio

Escreva ("Digite o valor do seu salário:  ")
leia(salario)

Escreva ("Digite o valor do seu aumento em %:  ")
leia(aumento)

valor <- ((salario*aumento)/100)

Escreval ("Seu salario erá de R$", salario, " e recebeu um aumento de", aumento, " porcento ou R$", valor, " assim totalizando um salario de R$", (salario+valor))

Fimalgoritmo